### ISSUE TITLE
Text in the Chinese version is not from The Art of War, by Sun Tsu

### ISSUE THREAD

**Issue by eyeplum** [iaolo/Desktop-Backgrounds#2]
In the blog post, it claims that the Chinese version uses _The Art of War, by Sun Tsu (孙子兵法)_:

    The desktop image is based on Hokusai’s The Great Wave off Kanagawa
    The waves are made of letters in iA Writer Duospace
    English and German uses the first chapter of Moby Dick as wave text
    French uses a chapter from Victor Hugo’s L’Homme qui rit
    Italian uses Alessandro Baricco’s Oceano Mare
    Spanish uses Don Quixote, by Cervantes
    The Portuguese get Pessoa’s The Book of Disquiet
    Chinese uses The Art of War, by Sun Tsu
    Japanese uses In Praise of Shaddows, by Tanizaki Junichiro

But the content in the picture is actually from _The Mathematical Classic of Master Sun (孙子算经)_ which is another treatise from a different author.

> The specific identity of its author Sunzi (lit. "Master Sun") is still unknown but he lived much later than eponymous Sun Tzu, author of The Art of War.

### References
- https://en.wikipedia.org/wiki/Sunzi_Suanjing
- https://zh.wikisource.org/zh/%E5%AD%AB%E5%AD%90%E7%AE%97%E7%B6%93
- https://en.wikipedia.org/wiki/The_Art_of_War

**Comment by iaolo** [comment]
Oops. Thank you. Corrected.
